# -*- mode: ruby -*-
# vi: set ft=ruby :

#require_relative './vagrant/key_authorization'

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'
#  authorize_key_for_root config, '~/.ssh/id_dsa.pub', '~/.ssh/id_rsa.pub'

  {
    'puppet' => '192.168.30.10',
    'ldap' => '192.168.30.11',
    'web' => '192.168.30.12',
    'db' => '192.168.30.13',
  }.each do |short_name, ip|
    config.vm.define short_name do |host|
      host.vm.network 'private_network', ip: ip
      host.vm.hostname = "#{short_name}.lab.local"
    end
  end
#  config.vm.provision "ansible" do |ansible|
#    ansible.playbook = "site.yml"
#  end
end
