# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|

  config.vm.provider "virtualbox" do |v|
        v.memory = 256
  end

  config.vm.box = 'ubuntu/trusty64'
  {
    'box-01' => '192.168.20.10',
    'box-02' => '192.168.20.11',
    'box-03' => '192.168.20.12',
#    'box-04' => '192.168.20.13',
#    'box-05' => '192.168.20.14',
  }.each do |short_name, ip|
    config.vm.define short_name do |host|
      host.vm.network 'private_network', ip: ip
      host.vm.hostname = "#{short_name}.ansiblelab.local"
    end
  end
end
